### ISSUE TITLE
Set InvariantCulture to current Thread

### ISSUE THREAD

**Issue by santanudasa108** [gopa810/GCAL-NET#1]
I've been having problems with app because it was converting the wrong way the latitude and longitude of locations beause of "." and ",". It was taking my current culture (Argentina-Buenos Aires) and it was calculating all wrong because of that.
Please consider setting:

```
System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
System.Threading.Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;

```
It can be insert in LoadInstanceData()

Hare Krishna

**Comment by gopa810** [comment]
Thanks. Done. Will be commited to main thread later on.
